version: '2'
volumes:
  mongo-db:
services:
  secrethitler:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - '8080:8080'
    links:
      - mongo
      - redis
  mongo:
    env_file:
      - .env
    image: mongo
    expose:
      - 27017
    volumes:
      - mongo-db:/data/db
  redis:
    env_file:
      - .env
    image: redis
    expose:
      - 6379
