version: '2'
volumes:
  mongo-db:
services:
  secrethitler:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - '8080:8080'
    links:
      - mongo
      - redis
  create-users:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.local
    links:
      - secrethitler
    entrypoint: bash -c 'while !</dev/tcp/secrethitler/8080; do sleep 1; done; yarn create-accounts'
  mongo:
    env_file:
      - .env
    image: mongo
    expose:
      - 27017
    volumes:
      - mongo-db:/data/db
  redis:
    env_file:
      - .env
    image: redis
    expose:
      - 6379
